### ISSUE TITLE
Make navigation bar position fixed

### ISSUE THREAD

**Issue by harshita214** [suubh/CodeClass#39]
**Is your feature request related to a problem? Please describe.**

Nav-bar position should be fixed so as if scrolled upwards user can still see navigation bar.
**Describe the solution you'd like**

I would like to add code for it.
**Describe alternatives you've considered**

**Additional context**
BEFORE 
![image](https://user-images.githubusercontent.com/79797000/136059450-429c245d-44d1-457c-b59c-2b4dc09bd69e.png)

AFTER
![image](https://user-images.githubusercontent.com/79797000/136059237-6c816852-9a0e-4838-8bcd-61f4bcce21cf.png)

**Comment by suubh** [comment]
Yes it will be great.

**Comment by harshita214** [comment]
okay will do it
