### ISSUE TITLE
Appealing scroll bar

### ISSUE THREAD

**Issue by harshita214** [suubh/CodeClass#41]
**Is your feature request related to a problem? Please describe.**
A custom scroll bar makes website look more professional.

**Describe the solution you'd like**
I would like to code for it

**Additional context**
BEFORE
![image](https://user-images.githubusercontent.com/79797000/136064733-e9c1f069-0fd6-4cf9-846c-f849188396b9.png)
 
AFTER
![image](https://user-images.githubusercontent.com/79797000/136064636-361edbe4-c2c9-4341-b517-d4d572d89e72.png)

**Comment by suubh** [comment]
Yah that look nice .👍🏻

**Comment by harshita214** [comment]
Okay will do it

**Comment by harshita214** [comment]
Done
