### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by harshita214** [suubh/CodeClass#42]
**Is your feature request related to a problem? Please describe.**
After enabling dark mode text should change like "Enable Light Mode!" but instead it remains same "Enable Dark Mode!"

**Describe the solution you'd like**
I can try to solve it.

**Additional context**
here's how it looks 
![image](https://user-images.githubusercontent.com/79797000/136065453-f7a42700-cb89-430f-8d98-9c620152dd7d.png)
This should be "light"

**Comment by suubh** [comment]
Thanks . If you want , you can work on it .

**Comment by harshita214** [comment]
Yes I will try to solve it

**Comment by musavveer** [comment]
Is the issue still open? I would like to give it a shot.
